import Hero from "@/Components/Hero";
import HowItWorks from "@/Components/HowItWorks";
import Head from "next/head";
import WhyChooseUs from "@/Components/WhyChooseUs";
import RentalDeal from "@/Components/RentalDeal";
import Testimony from "@/Components/Testimony";





export default function Home() {
  return (
    <>
      <Head>
        <title>rentAride</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Hero />
      <HowItWorks />
      <WhyChooseUs />
      <RentalDeal />
      <Testimony />
      
      
      
    </>
  );
}
